### ISSUE TITLE
Youtube link is invalid syntax?

### ISSUE THREAD

**Issue by HyperActive1DUK** [alan1world/yt_chapters#7]
I believe I've installed everything correctly, however upon running the line;

yt_chapters.py --split "https://www.youtube.com/watch?v=5CyezVfR_lA"

I get a syntax error highlighting the entire Youtube link. I'm fairly new to Python, so I'm not exactly sure what I'm doing wrong, but I'll try my best to answer any questions.

**Comment by alan1world** [comment]
Works for me.

I get the following files:

>'Maniac - Maniac (Full Album) 1985 - (1.You Don'\''t Know It).mp4'  
'Maniac - Maniac (Full Album) 1985 - (2.Get Ready).mp4'  
'Maniac - Maniac (Full Album) 1985 - (3.Dressed to Kill).mp4'  
'Maniac - Maniac (Full Album) 1985 - (4.God of Thunder).mp4'  
'Maniac - Maniac (Full Album) 1985 - (5.Ride On).mp4'  
'Maniac - Maniac (Full Album) 1985 - (6.Shout it Loud).mp4'  
'Maniac - Maniac (Full Album) 1985 - (7.Stage Free).mp4'  
'Maniac - Maniac (Full Album) 1985 - (8.We Swear at You).mp4'  
'Maniac - Maniac (Full Album) 1985.mp4'

Did you try running it without `--split` to see if the main installation is working?

Also: please post your actual error rather than saying "I get a syntax error highlighting the entire Youtube link". There's nothing wrong with the syntax.

**Comment by HyperActive1DUK** [comment]
Tried without the --split, did the same thing. The error simply says;

SyntaxError: invalid syntax

**Comment by alan1world** [comment]
Does youtube-dl work? You won't get the chapters but you will get the download.

Do other python scripts run successfully?

Are you on Windows? Mac? Linux?

Are you running in a Windows command line, Powershell window, bash shell etc.?

Since the code works and I tested your link this evening, it must be something in your configuration or the way you are running it.

**Comment by HyperActive1DUK** [comment]
youtube-dl is working as intended.

Other scripts are working fine.

On Windows 10 Education edition (64-bit).

Running in Windows command line, tried with and without Python running.

**Comment by alan1world** [comment]
Did you download via git clone or by copying the code into your own file?

The active file in the repo is called `yt_chapters`, not `yt_chapters.py` - you probably have file extensions hidden and didn't notice. On Linux you don't need the `.py` extension as the associations work differently.

Try renaming the script to `yt_chapters.py`. Not sure why Windows would say `SyntaxError: invalid syntax` when trying to call a file that doesn't exist.

**Comment by HyperActive1DUK** [comment]
I copied the code into my own file and the file extension isn't hidden.

**Comment by alan1world** [comment]
Then I'm sorry to say it's either the way you have copied it or your system configuration.

The code itself isn't generating the `SyntaxError: invalid syntax`, I have tested this twice, both with my local copy and cloning the repository. Both work correctly.

I would strongly suggest your redownload using `git clone https://github.com/alan1world/yt_chapters.git yt_chapters` and then running the file from in there.
