### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by TheFishy07** [alan1world/yt_chapters#8]
Hello. I am not understanding how to use this tool. I downloaded the python file and didn't touched it, is there anything that i need to change in it? how is the program supposed to know which video I wanna download?
When I run the file Im getting this:
`usage: ytb dwlnd with chaps.py [-h] [--split] [--test] [--fix] N [N ...]
ytb dwlnd with chaps.py: error: the following arguments are required: N`

**Comment by alan1world** [comment]
You should first read up on how to use the underlying youtube-dl library and make sure you understand the basic process. This script is an expansion to help with chapters.

Google will give you many guides, such as https://ostechnix.com/youtube-dl-tutorial-with-examples-for-beginners/

The full documentation for youtube-dl can be found here: https://github.com/ytdl-org/youtube-dl/blob/master/README.md#readme

**Comment by TheFishy07** [comment]
@alan1world Okay I think that I now understood what youtube-dl is and figured out how to use the commands. But when I do the `.\youtube-dl.py --test "https://youtu.be/pvkTC2xIbeY"` or `.\youtube-dl.py --split "https://youtu.be/pvkTC2xIbeY"` it doesn't do anything.
![image](https://user-images.githubusercontent.com/80952792/160894405-a3eda033-3cc3-4295-a8aa-0d809eeb56aa.png)

**Comment by alan1world** [comment]
> @alan1world Okay I think that I now understood what youtube-dl is and figured out how to use the commands. But when I do the `.\youtube-dl.py --test "https://youtu.be/pvkTC2xIbeY"` or `.\youtube-dl.py --split "https://youtu.be/pvkTC2xIbeY"` it doesn't do anything. ![image](https://user-images.githubusercontent.com/80952792/160894405-a3eda033-3cc3-4295-a8aa-0d809eeb56aa.png)

Yes, it won't do anything. `youtube-dl.py` and `yt_chapters` are different programs.  
If you read the documentation for `youtube-dl.py`, it doesn't have an option for `--test` or `--split`, that's why the chapter script was written.

Also, if you look at the error message you posted, it's saying that youtube-dl is not in the location you are trying to run it from, which is an entirely different issue.

**Comment by TheFishy07** [comment]
> > @alan1world Okay I think that I now understood what youtube-dl is and figured out how to use the commands. But when I do the `.\youtube-dl.py --test "https://youtu.be/pvkTC2xIbeY"` or `.\youtube-dl.py --split "https://youtu.be/pvkTC2xIbeY"` it doesn't do anything. ![image](https://user-images.githubusercontent.com/80952792/160894405-a3eda033-3cc3-4295-a8aa-0d809eeb56aa.png)
> 
> Yes, it won't do anything. `youtube-dl.py` and `yt_chapters` are different programs. If you read the documentation for `youtube-dl.py`, it doesn't have an option for `--test` or `--split`, that's why the chapter script was written.
> 
> Also, if you look at the error message you posted, it's saying that youtube-dl is not in the location you are trying to run it from, which is an entirely different issue.

It still isn't doing anything, and I know it's a different issue and I fixed the one of youtube-dl not being in the location im trying to run it from.
![image](https://user-images.githubusercontent.com/80952792/161316535-455bb19c-3fa5-49ea-8019-82f0ac236b82.png)
that's the location folder from where I am running the file:
![image](https://user-images.githubusercontent.com/80952792/161316643-e7deb5ad-969c-47ee-9e75-ca96079a608f.png)

**Comment by alan1world** [comment]
"It still isn't doing anything" is not an error description.

- Have you tried running `youtube-dl.exe` to see if it works?
- The code is based on `youtube-dl`, not `youtube-dl.exe` and therefore will likely not pick up the file
- I can't guarantee it will read `youtube-dl.exe` from the same directory. It should do. It may have to be added to your PATH in order for it to be detected. Otherwise, and this is what I would suggest, is that all references in the code to `youtube-dl` should - for you on your machine - be changed to a fully expanded path program call e.g. `result = subprocess.run(["youtube-dl"` becomes `result = subprocess.run(["D:\Users\Jean Paul\OneDrive\Progamming\JP\Python\ytb dwnlnd with chaps\youtube-dl.exe`
- Also, this being Windows, in a PowerShell console, in a OneDrive folder, it may require `shell=true` in order to run properly.

**Comment by TheFishy07** [comment]
> * The code is based on `youtube-dl`, not `youtube-dl.exe` and therefore will likely not pick up the file

Hello, so with `.\youtube-dl --test "https://youtu.be/pvkTC2xIbe"` this showed up in the terminal and a file got downloaded:
![image](https://user-images.githubusercontent.com/80952792/166114861-02b01c7f-eda0-4929-8575-a700f7c6b31d.png)
![image](https://user-images.githubusercontent.com/80952792/166114882-64e43e77-55f3-4cd8-b1cb-27764ff5685a.png)
 
 > * Also, this being Windows, in a PowerShell console, in a OneDrive folder, it may require shell=true in order to run properly.
 
 I changed the folder from `D:\Users\Jean Paul\OneDrive\Progamming\JP\Python\ytb dwnlnd with chaps` to `D:\Users\Jean Paul\Documents\ytb_dwlnd_chaps`
 

Now the problems are:

1. The downloaded video gives me an error when I open it:
![image](https://user-images.githubusercontent.com/80952792/166114967-2860185c-3e7b-439f-ac93-df87fca4032f.png)

2. The --split function isn't working
![image](https://user-images.githubusercontent.com/80952792/166115112-f484a132-7ead-4e16-bf1c-143997ac1eb3.png)
